name: CI
on: [push]
jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    runs-on: ubuntu-latest
    name: 'crystal: ${{ matrix.crystal }}'
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.0.0
          - 1.1.1
          - 1.2.0
        include:
          - crystal: nightly
            stable: false
    services:
      rethink:
        image: rethinkdb:2.4
        ports:
          - 29015:29015
          - 28015:28015
    continue-on-error: ${{ !matrix.stable }}
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - run: shards install --ignore-crystal-version
      - run: crystal spec -v --error-trace
