name: CI
on:
  push:
  schedule:
    - cron: "0 1 * * 0" # Every Sunday at 1:00

jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
